# Generated by Django 2.1.3 on 2018-12-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('source', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='friendshipinvitation',
            unique_together={('inviting', 'invited')},
        ),
    ]
