# Generated by Django 2.1.2 on 2018-10-28 16:17

from django.db import migrations, models
import profiles.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uuid', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
            managers=[
                ('objects', profiles.managers.ProfileManager()),
            ],
        ),
    ]
